#include "asn1.h"

ASN1_SEQUENCE(PAILLIER_PRIVATEKEY) = {
    ASN1_SIMPLE(PAILLIER_PRIVATEKEY, n, ASN1_INTEGER),
    ASN1_SIMPLE(PAILLIER_PRIVATEKEY, g, ASN1_INTEGER),
    ASN1_SIMPLE(PAILLIER_PRIVATEKEY, lambda, ASN1_INTEGER),
    ASN1_SIMPLE(PAILLIER_PRIVATEKEY, mu, ASN1_INTEGER)
} ASN1_SEQUENCE_END(PAILLIER_PRIVATEKEY)

ASN1_SEQUENCE(PAILLIER_PUBLICKEY) = {
    ASN1_SIMPLE(PAILLIER_PUBLICKEY, lambda, ASN1_INTEGER),
    ASN1_SIMPLE(PAILLIER_PUBLICKEY, mu, ASN1_INTEGER)
} ASN1_SEQUENCE_END(PAILLIER_PUBLICKEY)

IMPLEMENT_ASN1_FUNCTIONS(PAILLIER_PRIVATEKEY)
IMPLEMENT_ASN1_FUNCTIONS(PAILLIER_PUBLICKEY)